### ISSUE TITLE
is this DNS application response TCP request?

### ISSUE THREAD

**Issue by linkec** [appserver-io/dnsserver#10]
Hi
same as title,is this DNS application response TCP request?
and if not, any tutorial or document of TCP response
Thanks.

**Comment by wagnert** [comment]
Hi, this is a usual DNS server that'll also respond TCP requests.

**Comment by linkec** [comment]
I have already do some tries on my code, but still have some problem.
I am not sure what the special of TCP response and UDP response. 
I just added the packet size before the packet and that's it.
But the test on http://dnscheck.pingdom.com/ seems not good.

**Comment by wick-ed** [comment]
Hi @linkec 

how is your setup exactly? Are you trying to reach a site you host from the internet using appserver DNS server?
That wont work as no outside service will ask appserver for name resolution without being explicitly configured to do so.
Our DNS server is more intended for local development so you do not have to tamper with your /etc/hosts or install dnsmasq separatly

**Comment by linkec** [comment]
I am trying to write a new authorized DNS backend for my CDN service. I have already implement EDNS on it and basic functions are running normal. But one wired thing was happens.
Some clients set them dns as 1.1.1.1, but response nothing. but for 8.8.8.8, they do response.
So I am looking for why was it happened. I am not sure about did I really implement TCP.
I tried use "dig +tcp" to have a test, it is works fine. 
So I am search for some information about this, and I see your github.

**Comment by linkec** [comment]
@wick-ed @wagnert

**Comment by wick-ed** [comment]
Sorry but I am totally not getting what your setup is.
Please answer:

Are you using appserver DNS?
Why do you think 1.1.1.1 or 8.8.8.8 should work with your setup (that does not require appserver)?
Where are the clients, on the internet or on your local machine?
